import type { Order } from "./types";

export const ORDERS: Order[] = [
  {
    id: "ord_2094",
    number: "AO-2094",
    customer: "Supermercado Silva",
    customerDetail: "Unidade Centro · CNPJ 12.345.678/0001-90",
    channel: "whatsapp",
    status: "attention",
    receivedAt: "há 2 min",
    aiConfidence: 68,
    message:
      "Bom dia, aqui é o João da Silva. Manda 10 caixas de skol latão 350ml e 5 fardos daquela água crystal. Ah, vê se tem coca 2L, se tiver manda 2 fardos tb. Valeu!",
    audioSeconds: 14,
    transcript:
      "10 caixas Skol Latão 350ml. 5 fardos Água Crystal 500ml. 2 fardos Coca-Cola 2L (se disponível).",
    items: [
      {
        id: "i1",
        rawMention: "10 caixas de skol latão 350ml",
        productName: "Skol Latão 350ml (CX 12)",
        sku: "80214",
        unit: "CX",
        qty: 10,
        unitPrice: 42.9,
        confidence: "high",
      },
      {
        id: "i2",
        rawMention: "5 fardos daquela água crystal",
        productName: "Água Crystal 500ml",
        sku: "—",
        unit: "FD",
        qty: 5,
        unitPrice: 18.5,
        confidence: "low",
        reason: "Ambiguidade detectada: Com gás vs Sem gás",
        alternatives: [
          { sku: "502", name: "Crystal Sem Gás 500ml" },
          { sku: "503", name: "Crystal Com Gás 500ml" },
        ],
      },
      {
        id: "i3",
        rawMention: "2 fardos coca 2L",
        productName: "Coca-Cola 2L (FD 6)",
        sku: "10452",
        unit: "FD",
        qty: 2,
        unitPrice: 58.2,
        confidence: "high",
      },
    ],
  },
  {
    id: "ord_2093",
    number: "AO-2093",
    customer: "Distribuidora Santos",
    customerDetail: "Matriz · CNPJ 09.887.221/0001-11",
    channel: "whatsapp",
    status: "ready",
    receivedAt: "há 12 min",
    aiConfidence: 98,
    message: "Repete o pedido da semana passada por favor.",
    transcript: "Repetir último pedido (ref. AO-2061).",
    items: [
      {
        id: "i1",
        rawMention: "pedido da semana passada",
        productName: "Heineken Long Neck 330ml (CX 24)",
        sku: "44120",
        unit: "CX",
        qty: 20,
        unitPrice: 128.0,
        confidence: "high",
      },
      {
        id: "i2",
        rawMention: "pedido da semana passada",
        productName: "Red Bull Energy 250ml (FD 24)",
        sku: "55009",
        unit: "FD",
        qty: 8,
        unitPrice: 219.9,
        confidence: "high",
      },
    ],
  },
  {
    id: "ord_2092",
    number: "AO-2092",
    customer: "Bar do Zé das Couves",
    customerDetail: "Vila Madalena · CNPJ 33.221.998/0001-04",
    channel: "whatsapp",
    status: "ready",
    receivedAt: "há 18 min",
    aiConfidence: 96,
    message:
      "Manda 3 caixas de água com gás e umas 2 de refri, qualquer marca de cola serve.",
    transcript:
      "3 caixas Água Com Gás 500ml. 2 caixas Refrigerante Cola 2L (marca flexível).",
    items: [
      {
        id: "i1",
        rawMention: "3 caixas de água com gás",
        productName: "Crystal Com Gás 500ml (CX 12)",
        sku: "503",
        unit: "CX",
        qty: 3,
        unitPrice: 32.4,
        confidence: "high",
      },
      {
        id: "i2",
        rawMention: "2 de refri qualquer marca",
        productName: "Coca-Cola 2L (FD 6)",
        sku: "10452",
        unit: "CX",
        qty: 2,
        unitPrice: 58.2,
        confidence: "mid",
        reason: "Marca não especificada — sugerida pela preferência histórica.",
      },
    ],
  },
  {
    id: "ord_2091",
    number: "AO-2091",
    customer: "Restaurante Recanto",
    customerDetail: "Pinheiros · CNPJ 41.009.882/0001-77",
    channel: "whatsapp",
    status: "processing",
    receivedAt: "há 32 min",
    aiConfidence: 0,
    message: "[áudio 0:47]",
    items: [],
  },
  {
    id: "ord_2090",
    number: "AO-2090",
    customer: "Padaria Aurora",
    customerDetail: "Tatuapé · CNPJ 22.118.443/0001-50",
    channel: "whatsapp",
    status: "ready",
    receivedAt: "há 45 min",
    aiConfidence: 99,
    message: "Pedido padrão de quarta. Obrigado!",
    items: [
      {
        id: "i1",
        rawMention: "padrão de quarta",
        productName: "Leite Integral 1L (CX 12)",
        sku: "70010",
        unit: "CX",
        qty: 6,
        unitPrice: 78.0,
        confidence: "high",
      },
    ],
  },
  {
    id: "ord_2089",
    number: "AO-2089",
    customer: "Hotel Marina Rio",
    customerDetail: "Copacabana · CNPJ 88.112.009/0001-22",
    channel: "whatsapp",
    status: "received",
    receivedAt: "há 1 h",
    aiConfidence: 0,
    message: "Bom dia, segue lista em anexo (foto).",
    items: [],
  },
  {
    id: "ord_2088",
    number: "AO-2088",
    customer: "Mercearia da Esquina",
    customerDetail: "Brás · CNPJ 67.221.554/0001-13",
    channel: "whatsapp",
    status: "failed",
    receivedAt: "há 2 h",
    aiConfidence: 0,
    message: "vcs entregam hj??",
    items: [],
  },
];
